const fs=require('fs'), path=require('path'), http=require('http');
const publicDir=path.resolve('marble-sort/android/app/src/main/assets/public');
const out=path.resolve('marble-sort/qa-home-v8.png');
const mime={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.mp3':'audio/mpeg'};
const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://x').pathname;if(p==='/')p='/index.html';let f=path.resolve(publicDir,'.'+decodeURIComponent(p));if(!f.startsWith(publicDir)||!fs.existsSync(f)){res.writeHead(404);res.end('not found');return}res.writeHead(200,{'content-type':mime[path.extname(f)]||'application/octet-stream','cache-control':'no-store'});fs.createReadStream(f).pipe(res);});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function ensureChrome(){try{await fetch('http://127.0.0.1:9333/json/version');return}catch{} const {spawn}=require('child_process');const cands=[process.env.ProgramFiles+'\\Google\\Chrome\\Application\\chrome.exe',process.env['ProgramFiles(x86)']+'\\Google\\Chrome\\Application\\chrome.exe',process.env.ProgramFiles+'\\Microsoft\\Edge\\Application\\msedge.exe'];const exe=cands.find(fs.existsSync);if(!exe)throw Error('No Chrome/Edge found');spawn(exe,['--headless=new','--remote-debugging-port=9333','--disable-gpu','--no-first-run','--no-default-browser-check','about:blank'],{detached:true,stdio:'ignore'}).unref();await sleep(1500)}
async function page(){let r=await fetch('http://127.0.0.1:9333/json/new?about:blank',{method:'PUT'});let t=await r.json();let ws=new WebSocket(t.webSocketDebuggerUrl);await new Promise((res,rej)=>{ws.onopen=res;ws.onerror=rej});let id=0,pending=new Map();ws.onmessage=e=>{let m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){let {res,rej}=pending.get(m.id);pending.delete(m.id);m.error?rej(Error(JSON.stringify(m.error))):res(m.result||{})}};let send=(method,params={})=>new Promise((res,rej)=>{let msg={id:++id,method,params};pending.set(msg.id,{res,rej});ws.send(JSON.stringify(msg));});return{send,close:()=>ws.close()}}
async function evalJS(pg,expression){let r=await pg.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value}
async function wait(pg,expr){for(let i=0;i<80;i++){if(await evalJS(pg,`Boolean(${expr})`).catch(()=>false))return;await sleep(100)}throw Error('timeout '+expr)}
server.listen(5184,'127.0.0.1',async()=>{try{await ensureChrome();let pg=await page();await pg.send('Page.enable');await pg.send('Runtime.enable');await pg.send('Emulation.setDeviceMetricsOverride',{width:360,height:800,deviceScaleFactor:2,mobile:true});await pg.send('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.setItem('marble-sort-state-v1', JSON.stringify({version:2,level:30,unlocked:30,coins:3010,lives:5,launched:true,onboarded:true,playerName:'QAPlayer',avatar:1,music:false,sound:false,vibration:false,boosters:{undo:3,shuffle:3,tube:3},boosterSeen:{undo:true,shuffle:true,tube:true},noAds:{active:false,until:null}}));`});await pg.send('Page.navigate',{url:'http://127.0.0.1:5184/index.html'});await wait(pg,`document.querySelector('.home')`);await sleep(700);let data=await pg.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(out,Buffer.from(data.data,'base64'));let rects=await evalJS(pg,`(() => ({icons:[...document.querySelectorAll('.home-float')].map(e=>{const r=e.getBoundingClientRect();return {cls:e.className,x:r.x,y:r.y,w:r.width,h:r.height}}), play:(()=>{const r=document.querySelector('.home-play').getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}})(), level:(()=>{const r=document.querySelector('.home-level-number').getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height,text:document.querySelector('.home-level-number').textContent.trim()}})()}))()`);console.log(JSON.stringify(rects,null,2));pg.close();}catch(e){console.error(e);process.exitCode=1}finally{server.close();}});
